### ISSUE TITLE
Blacklist is not saved

### ISSUE THREAD

**Issue by seguri** [lengstrom/falcon#30]
Open preferences, add a site, save, reload preferences: new rule is gone.

**Comment by andrewilyas** [comment]
Should be fixed!

**Comment by seguri** [comment]
Seems fixed :)

**Comment by lengstrom** [comment]
Yeah, we haven't updated the Chrome extension yet, just the repository!

**Comment by seguri** [comment]
I saw so I did a "transparent installation" but version was the same :)
