### ISSUE TITLE
Credit Min for project inspiration?

### ISSUE THREAD

**Issue by jsejcksn** [lengstrom/falcon#57]
I'm not positive that you got the idea from [Min](https://github.com/minbrowser/min), but it seems likely.

**Comment by lengstrom** [comment]
I've never heard of Min, thanks for the information! This project was largely inspired by the MacOS Spotlight. The original project was really different from its current form, you can read about it here: http://devpost.com/software/falcon-m5zehr.

**Comment by jsejcksn** [comment]
@lengstrom Maybe you guys could team up!
