### ISSUE TITLE
Falcon opens https://github.com/lengstrom/falcon every time it is updated

### ISSUE THREAD

**Issue by Tyilo** [lengstrom/falcon#65]
Every time falcon is updated it opens https://github.com/lengstrom/falcon which is somewhat annoying.

**Comment by Tatsh** [comment]
It seems to open every time I restart the browser here. Shameless promotion!

**Comment by lengstrom** [comment]
There's something wrong with your browser, that should not happen. What
version of Chrome? Did you install off of web store?
ᐧ

**Comment by Tatsh** [comment]
I thought it was happening. It seemed like it was happening. I did a full quit and it did not show up. Perhaps it was updated at the time. So the original bug still stands as is.

**Comment by lengstrom** [comment]
No, Falcon has not been updated in months.
ᐧ
