### ISSUE TITLE
We added support for existing History, Bookmarks and PDFs. Want to collaborate?

### ISSUE THREAD

**Issue by oliversauter** [lengstrom/falcon#66]
Hey folks, 

I tried to contact @lengstrom via linkedIn and Facebook a few weeks back, but without a response. 
It would be great to collaborate in the future on the open-source project we are building. 

We have forked your tool and added the ability to import the existing history and bookmarks, as well as PDF support.
At the [WorldBrain project](http://worldbrain.io), we are further developing it into a search-engine for the complete digital knowledge of a user. More about that you can see in our [2 min intro video.](http://worldbrain.io/intro)

In the long-term we want to battle online misinformation by making it possible to effortlessly share trustworthy websites/content/notes with followers and let them search through them. (among other important features). This is reflected in our [3,5 min vision video](http://worldbrain.io/vision)

I've seen that you have not been working on the tool in the recent months. So anybody who is interested in continuing these efforts, I invite to contribute to our project. 

Just write me an email under oli@worldbrain.io.

Happy 2017 :)
Oliver

**Comment by lengstrom** [comment]
Oliver -- It's great you're building off of our work, and your work seems interesting! I never received any of your communication attempts, sorry :) 

One request: please refrain from advertising on the Falcon GitHub page. Falcon and its derivatives (by their nature) handle very sensitive data, and I don't want anyone to think that another project is a successor for or endorsed by Falcon. 

Good luck with your project!

**Comment by oliversauter** [comment]
Hey Logan!

> I never received any of your communication attempts, sorry 

They must have been ended up in the other mailbox on Facebook. 

If you are interested in collaborating on this, lets continue the convo via email. (oli@worldbrain.io)
With the WorldBrain project, we aim to produce as many reusable libraries as possible, so that many different variations of the client can co-exist - hence also falcon can reuse them.
At the end its about that we gather a diverse community of people working in a variety of disciplines and letting them share content recommendations with each other. 

> One request: please refrain from advertising on the Falcon GitHub page.

Sure, no problem. 

Another question: What is your reasoning for chosing GPL3 as the license?
