### ISSUE TITLE
Release new version on chrome webstore

### ISSUE THREAD

**Issue by Tyilo** [lengstrom/falcon#70]
Falcon is very annoying to use with Google Chrome Dev without https://github.com/lengstrom/falcon/commit/525f3b1aceea0ca46df6f642e4a9f1b33b3ddbde

**Comment by rzr999** [comment]
It's a reminder that you have it installed 😄

**Comment by ldong** [comment]
@lengstrom By the way, what is the difference between [WorldBrain](https://chrome.google.com/webstore/detail/worldbrain-the-research-e/abkfbakhjpmblaafnpgjppbmioombali) in a nutshell? I like falcon for it does no more than get the job done. WorldBrain seems to be over-engineered.

**Comment by lengstrom** [comment]
WorldBrain is a fork of Falcon. I'm not sure what the differences between Falcon and WorldBrain are. That said I would use any project with a similar function as Falcon (including Falcon!) very carefully - there are obvious potential privacy/data problems that can occur. Use it at your own risk (although it is open source, so you can audit it yourself).

**Comment by oliversauter** [comment]
Hey folks! 

I am one of the people running the WorldBrain project. 

For now the only major differences between the two projects are that WorldBrain offers the import of existing history items, your bookmarks as well as PDF support. 

Later on we also make other places searchable that you use to organise your knowledge. (Evernote etc.). More on that you can learn about in our vision video: worldbrain.io/vision.

And yes, I have to agree with @lengstrom. Indeed Full-text search has its privacy issues, but I think with the blacklist, Falcon made a good first step to lower the risk of identity theft etc. 
There is surely more to do, like "blacklist & forget" options to delete stuff in retrospect or encrypting the raw data.

**Comment by lengstrom** [comment]
The new version (0.2.4) has been published on the Web Store!
